### ISSUE TITLE
Fix : Issue when creating new user and duplicate username with capitals exits.

### ISSUE THREAD

**Issue by Fraser-Levack** [Team-5A/DjangoJam#28]
### eg. exception is raised when I try to create a user called "fraser" when the user "Fraser" exists. Due to slug duplication. possible fixes include : 

1. Raise alert and stop the user being created making the client enter a different name (Easy solution)
2. Allow the user to create a new user and figure out a way to not get a duplication (non unique) error. (Maybe possible by adding numbers or letters to slug to create unique however must be mapped (Hard solution)  

Thanks

**Comment by freddie-nelson** [comment]
What if we just compare usernames based on lowecase version so 'Fraser' and 'fraser' are treated as equivalent and then on registration we can just not allow it and show username already taken error.

What do you think? I could get this implemented later if sounds good

**Comment by freddie-nelson** [comment]
fixed in #30 for tunes and users
